### ISSUE TITLE
continue reading log from last execution (feature)

### ISSUE THREAD

**Issue by bbrendon** [phbits/WebsiteFailedLogins#1]
I tried this and I'm getting alerts for every execution when running `Invoke-WebsiteFailedLogins` . (as long as there is a failed login within the time period configured). 

It would be nice if this was like fail2ban where it continued reading the log file from where it previously left off.

**Comment by phbits** [comment]
I used that method on an early iteration and found it didn't work very well. Depending on the timing of everything, failed logins could fall below the threshold when it should have in fact been caught. Having an adjustable window is the better approach.

Reading logs serially would change the entire module and logic behind it. Requiring persistence of not only the last record read but also a state of failed logins during the specified window. That "state" would then need to be incorporated with the next run-time window if they overlap.

If your concern is having Logparser go through an entire folder of log files each time, consider keeping only a few days worth of logs in that folder and moving all others to an "Archive" folder. This way IIS can log to faster disk (i.e. SSD) while the older logs can reside on slower storage. A PowerShell one-liner to achieve this would look something like following. Set it up via `Scheduled Tasks` and you're good to go.

```powershell
Get-ChildItem -Path D:\IIS-Log-Path\ -Filter "u_ex*.log" | ?{ $_.LastWriteTime -lt (Get-Date).AddDays(-3) } | %{ Move-Item -LiteralPath $($_.FullName) -Destination D:\IIS-Log-Archive\ }
```

**Comment by phbits** [comment]
This enhancement isn't on the roadmap for the foreseeable future due to the reasons mentioned earlier.
