### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by mguinness** [phbits/WebsiteFailedLogins#2]
I tried to do something similar and created a [gist](https://gist.github.com/mguinness/e8e1cbf99d2596f37d7c7b9909ca88f0) for the script.  Yours is much better so maybe you can take a couple of ideas from mine which is auto blocking IP's and reporting them to AbuseIPDB website.

**Comment by phbits** [comment]
Hi @mguinness! Thanks for the gist and suggestions! I'm working to finish up a DSC related project and wanted to provide you with a solution. The requirement is for WebsiteFailedLogins to log alerts via the Event Log. Then perform the following.

1. Create custom script: [Application-EventID10.ps1](https://gist.github.com/phbits/c18e7993605ce3f6f6f075523e555c13)
This script will be launched for each event generated. The `RecordID` is passed to the script which it uses to retrieve the triggering event. From there you can perform any tasks you'd like. Save the script as `C:\WebsiteFailedLogins\Application-EventID10.ps1`

2. Create Event Trigger: [Create-EventTrigger.ps1](https://gist.github.com/phbits/6c927dcc478af6e91248c9d075096c0a)
As the name suggests, this creates an event trigger to pass the `RecordID` to whatever PowerShell script you want. In this case it will be the script mentioned above.

I've tested both of these and verified they work as expected. Granted they were running as `SYSTEM` so if you're doing proper delegation of privilege then there will be some fine tuning.  

The above solution only addresses failed logins per IP. If you're interested to perform action when `TotalFailedLogins` is triggered, use the same method and update `EventID = 20`.

Hope this helps!

Paul

**Comment by mguinness** [comment]
Thanks for those scripts, that's a clever way to leverage the event logs generated from your other script.

Hopefully others will find these scripts useful too, the more people that report to AbuseIPDB the better.

**Comment by phbits** [comment]
@mguinness - Thanks again for the suggestions! Wanted to let you know I just published v2.0 of this module which is a significant improvement. Lots of documentation on the [wiki](https://github.com/phbits/WebsiteFailedLogins/wiki).

**Comment by mguinness** [comment]
Thanks for the update and for the documentation in the wiki.
